### ISSUE TITLE
Create new Workspace with Safari

### ISSUE THREAD

**Issue by marco55555** [puria/ksweb#36]
MacOS 10.12.6 (16G1212) and Safari 11.0.3 (12604.5.6.1.1) do not allow to create new Workspace

**Comment by puria** [comment]
I was not able to reproduce it. Which user? Gives an error, in the console?

**Comment by puria** [comment]
Tried and in any way I'm able to create workspaces. I guess could be related to #37 that is already closed. So will close this for now.

**Comment by puria** [comment]
#37
