### ISSUE TITLE
New Workspace with name already used

### ISSUE THREAD

**Issue by marco55555** [puria/ksweb#37]
I can't create a new Workpace with name "prova" with my account.

I get the following debug feedback:

Object { workspace_name: "prova" } prova  start:139:17
Object { readyState: 4, getResponseHeader: .ajax/E.getResponseHeader(), getAllResponseHeaders: .ajax/E.getAllResponseHeaders(), setRequestHeader: .ajax/E.setRequestHeader(), overrideMimeType: .ajax/E.overrideMimeType(), statusCode: .ajax/E.statusCode(), abort: .ajax/E.abort(), state: .Deferred/i.state(), always: .Deferred/i.always(), catch: .Deferred/i.catch(), altri 10… } error  start:150:21

Workspace "prova" didn't exist in my user area.

I see it exists a Workspace named "prova" for user "demo".

My guessing is that I can't create a Workspace "prova" with my user because it already exists with user "demo".

**Comment by puria** [comment]
Correct guess 😸 it is a heritage of the common workareaa for all users... should be fixed to allow duplicate names
