### ISSUE TITLE
Export file: make easy analyzing diff

### ISSUE THREAD

**Issue by marco55555** [puria/ksweb#52]
Analyzing differences among versions of the json file exported from KS could be easier if two issues are solved:
- Outputs are saved in one single (sometimes very long) lines,
- when you import a file in a workspace and export it again all the identifiers of the nodes are changed.
I wonder how this issues could be addressed.

**Comment by Emilio-Cascio** [comment]
Buongiorno.Ho avuto un problema di "esplosione" con un file .json.Ti posso inoltrare la sequenza che mi porta al problema ?Grazie.ing. Emilio Cascioviale XXV Luglio, 4110090 San Giusto Canavese+393420707227info@emiliocascio.itemilio.cascio@ingpec.euIl 05 dic 2018 7:57 AM, Puria Nafisi Azizi <notifications@github.com> ha scritto:Closed #52.

**Comment by puria** [comment]
Certo! Per cortesia, se possibile aprimi una nuova Issue ;)
